name: "Setup AWS CodeArtifact"
description: "Sets up the dotnet build environment to use AWS CodeArtifact"
inputs:
  action-message:
    description: 'Custom Message to include'
    required: true
  action-status:
    description: "Custom status to display"
    required: false
    default: ${{ job.status }}

runs:
  using: "composite"

  steps: 
  # Call the action provider
  - name: Invoke Slack Action
    uses: act10ns/slack@v1
    with:
      status: ${{ inputs.action-status }}
      channel: '#build-events'
      message: ${{ inputs.action-message }}
    if: always()
