name: "Setup AWS CodeArtifact"
description: "Sets up the dotnet build environment to use AWS CodeArtifact"
inputs:
  action-message:
    description: 'Custom Message to include'
    required: true

runs:
  using: "composite"

  steps: 
  # Call the action provider
  - name: Invoke Slack Action
    uses: act10ns/slack@v1
    with:
      status: ${{ job.status }}
      channel: '#build-events'
      message: ${{ inputs.action-message }}
    env: 
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    if: always()
